.github/workflows/rust.yml
=> Fix Rust CI trigger

github-webhook/build.rs
=> cargo clippy --fix

renovate.json
=> Renovate review request config

.github/workflows/validate-renovate.yml
Renovate を dry-run する CI を作る https://zenn.dev/azrsh/articles/renovate-dry-run-ci
=> Add Renovate dry-run CI

renovate.json
- https://github.com/octokit/webhooks のバージョンを Renovate で更新する
=> Renovate octokit/webhooks version

renovate.json
- https://docs.renovatebot.com/configuration-options/#configmigration
=> Enable Renovate config migration

Cargo.toml
=> Set workspace dependencies version for packaging crate

Cargo.lock, Cargo.toml, dts-downloader/Cargo.toml, github-webhook/Cargo.toml, type-generator/Cargo.toml
=> Release  v0.2.0

.github/workflows/rust.yml
=> Use dtolnay/rust-toolchain action instead of actions-rs/toolchain

.github/workflows/rust.yml
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://github.com/sksat/rust-template/pull/108
=> Bye set-output

.github/workflows/rust.yml
- Resolve #5 
- GitHub Pages に rustdoc をデプロイする
=> Add rustdoc build job

README.md, github-webhook/Cargo.toml
=> Add README

Cargo.lock, Cargo.toml, dts-downloader/Cargo.toml, dts-downloader/src/lib.rs, github-webhook/Cargo.toml
use `semver` crate to parse build metadata
=> Fix version handling

Cargo.lock, github-webhook/Cargo.toml, github-webhook/tests/parse-payload-example.rs
=> Add test by octokit/webhooks payload-example

Cargo.lock, Cargo.toml
- #79 
- https://github.com/octokit/webhooks/pull/800
=> Release v0.3.0

github-webhook/Cargo.toml
- そもそもあるべき
- たぶんこれのせいで #81 がコケる
=> Enable serde derive feature

Cargo.lock, Cargo.toml, dts-downloader/Cargo.toml, type-generator/Cargo.toml
=> Remove unused dependencies

.github/workflows/rust.yml, github-webhook/Cargo.toml
- https://github.com/obi1kenobi/cargo-semver-checks
- https://github.com/obi1kenobi/cargo-semver-checks-action
=> Add semver check CI job

Cargo.lock, Cargo.toml
=> Release 0.3.2

.github/workflows/rust.yml, rust-toolchain
=> Add install components via rust-toolchain

Cargo.toml, dts-downloader/Cargo.toml, github-webhook/Cargo.toml, type-generator/Cargo.toml
- #96 
- https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
=> Add MSRV as package.rust-version

.github/workflows/rust.yml
Reverts sksat/github-webhook-rs#104
=> Revert "Update actions/upload-pages-artifact action to v1.0.9"

Cargo.lock, Cargo.toml
=> Bump version to 0.5 for internal dep breaks

.github/workflows/rust.yml
=> Fix rustdoc file permission for actions/upload-pages-artifact v2

github-webhook/tests/parse-payload-example.rs, type-generator/src/to_tokens.rs
=> clippy --fix

type-generator/src/dag.rs
=> Use `#[cfg]` instead of `cfg!`

.github/workflows/rust.yml
=> Specify actions/checkout minor, patch version

renovate.json
=> Pinning GitHub Action digests by Renovate

Cargo.lock, Cargo.toml
=> Reference internal deps crates via crates.io

Cargo.lock, Cargo.toml
Reverts sksat/github-webhook-rs#193
- https://github.com/sksat/github-webhook-rs/pull/193#issuecomment-1890774119
=> Revert "Reference internal deps crates via crates.io"

.github/workflows/rust.yml
=> Add MSRV verify CI job

Cargo.lock, dts-downloader/Cargo.toml, dts-downloader/src/lib.rs, github-webhook/Cargo.toml, github-webhook/tests/parse-payload-example.rs
=> Use crate minreq instead of reqwest
